/**
 * Défini les constantes du jeu.
 */

const [SCREEN_WIDTH, SCREEN_HEIGHT] = [1080, 600];
const [SCREEN_CENTER_WIDTH, SCREEN_CENTER_HEIGHT] = [SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2];

const [BAR_WIDTH, BAR_HEIGHT] = [1080, 50];
const [BAR_CENTER_WIDTH, BAR_CENTER_HEIGHT] = [BAR_WIDTH / 2, BAR_HEIGHT / 1.85];
const BAR_TEXT_SIZE = BAR_HEIGHT / 2;

const SCREEN_NAMES = {
	MENU: 'menu',
	GAME: 'game',
}

const [BUTTON_WIDTH, BUTTON_HEIGHT] = [SCREEN_WIDTH / 1.5, 75];
const BUTTON_CENTER_X = (SCREEN_WIDTH - BUTTON_WIDTH) / 2;

const COLORS = {
	BLUE: [10, 10, 255],
	GREEN: [10, 255, 10],
	RED: [255, 10, 10],
	YELLOW: [255, 204, 100],
	WHITE: [255],
	LIGHT_GREY: [200],
	GREY: [50],
	BLACK: [5],
};